#+SETUPFILE: ~/.emacs.d/org-templates/level-0.org
#+title: El Baul del Programador
#+date: <2020-09-25 Fri>
# #+INCLUDE: sitemap.org
#+options: toc:nil

Welcome to my blog! I am a mix between Computer Scientist & Data Scientist. Keen on Functional Programming & Machine Learning. Right now I am working as Data Engineer [[https://www.moia.io/en][@MOIA]]

You can see a list of my [[file:org-posts/index.org][latest posts here]]. I migrated this blog from hugo to org-mode, you can find the old [[./index.old.html][index page here]].

* Personal projects
** [[https://github.com/elbaulp/DPASF][DPASF (Data Pre-processing Algorithms for Streaming in Flink)]]
   This is my MSc on Data Science final project. This is a library for Data Pre-processing Algorithms for Streaming in Flink (DPASF). It has an associated publication (currently a pre-print on [[https://arxiv.org/abs/1810.06021][ArXiv]]).

** [[https://github.com/elbaulp/Scala-Category-Theory][Scala-Category-Theory]]
   Bartosz Milewski great book on Category Theory implemented in scala, with property Tests

** [[https://github.com/elbaulp/grado_informatica_criptografia][Cryptography Exercises]]
   A repo hosting all the assigment and source code of the Cryptography course on the University of Granada.

** [[https://github.com/elbaulp/hugo_similar_posts][Hugo Similar Posts]]
   Computing similar posts for my blog using Sklearn Kmeans, you can read more about this project in the blog post: [[https://elbauldelprogramador.com/en/related-posts-hugo-sklearn/][Show related posts in Hugo with Sklearn]].

** [[https://github.com/elbaulp/NLP_Dependency_Parsing][NLP Dependency Parsing for Spanish]]
   Final project of my Computer Science degree. This software is an implementation of a Dependency parser for Spanish, using SVMs.

** [[https://github.com/elbaulp/myDWM][My Personal DWM fork]]
   Personal Fork of DWM, It has two branches, master that is as the original dwm and has a simple status color patch, and myconfig, that as its name point, is my personal config of DWM.

** [[https://github.com/elbaulp/genPlaylistByName][Generate Playlist By Length]]
   A little python script for generate playlist with a given length in minutes. You can read more about this in the post [[https://elbauldelprogramador.com/en/generar-listas-de-reproduccion-determinada-duracion-python/][/Create music playlists with a given length/]]
