#+setupfile: ../static/org-templates/level-1.org
#+title: A thought about this blog
#+date: <2021-02-23 Tue>
#+category: misc

It has been a while since I last wrote something in this blog, and I feel sorry about it, because I created it back in 2007 and we are now in 2021, so this blog has been with me since the begining of my journey with computers. The frequency of post has been decreasing dramatically since 2007, but I also think the quality of the posts have been increasing, or at least I hope.

It's not that I have runned out of ideas, it's that I think I have become more strict about the quality of the posts I want to write. Usually when I have an idea, I think: /does this add value to the comunity?, is it something that someone else has already written about?/. And given the amount of resources and blogs, the answer is usually *yes*, so I tend to not write the post. Even the post I wrote a while ago about [[file:migrating-from-hugo-to-org-mode.org][migrating the blog to emacs]] or the one about [[file:deploy-telegram-bot-aws-lambda-free.org][deploying a telegram bot to AWS lambda]], that felt like I was not adding value to the community, because there are quite a few posts about it on the internet.

Besides all of the above, I do not even know if people is reading the blog at all (If you do, feel free to drop a comment below, or say something on [[https://twitter.com/ElBaulP/status/1364193433259286534][twitter]] or [[https://t.me/elbaulp/1748][telegram]]).

Wrapping up, I hope next time I post, the content would be of an acceptable quality.
